### ISSUE TITLE
`Renderer.To_Texture` Problem

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#102]
Since merging the latest Develop branch, programs calling `Renderer.To_Texture` fail with:
~~~
Texture_Management.Render_Text calling Renderer.To_Texture
An exception occurred in Texture_Management.Render_Text.
An exception occurred in Main_Loop.
Render_Text returned a constraint error: 
raised CONSTRAINT_ERROR : gl-objects-framebuffers.adb:256 access check failed
~~~
The ` exception occurred in Texture_Management.Render_Text`  message appears to have been generated by a call to `Renderer.To_Texture`.
This problem occurs both in the example program `Text_Rendering_2` and another project.
I inserted the `Texture_Management.Render_Text calling Renderer.To_Texture` message for debugging purposes, a similar line also being added following the call to `Renderer.To_Texture` which, of course, did not execute.

**Comment by flyx** [comment]
I made changes to `GL.Objects` recently and there is probably a bug in there. will investigate.
