### ISSUE TITLE
GLUT use

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#112]
I am working on a project that uses `glutSolidTeapot` which I have implemented in Ada.
Is it possible to use this?
If so, are there other GLUT functions that I need to implement in OpenGLAda?
If not possible, do you know of any way of rendering the "standard" teapot under `GLFW`
Thanks for any assistance.

**Comment by flyx** [comment]
The teapot is a complex 3D model and therefore is not part of GLFW, as GLFW's job is not to provide you with rendering data.

I do not want to have GLUT functions in OpenGLAda; GLUT is pretty much obsolete and that teapot is quite definitely rendered using deprecated OpenGL functionality. I do not want to confuse users by providing a binding to an obsolete API.

You can of course import GLUT functionality in your project.

**Comment by rogermc2** [comment]
I absolutely agree that  GLUT functions do not belong in OpenGLAda.
Thanks for your advice with which I totally agree.
