### ISSUE TITLE
procedure Map question

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#113]
~~~
procedure Map (Target : in out Buffer_Target; Access_Type : Access_Kind;
                  Pointer : out Pointers.Pointer);
~~~
In the above, is `Target : in out Buffer_Target` correct, or should it be `Target : Buffer_Target`?
The same would apply to `procedure Unmap`.

**Comment by flyx** [comment]
Indeed. Doesn't make sense of having in `in out` since the targets are constant.

**Comment by rogermc2** [comment]
As this is a simple fix, is it OK if I mend it me current PR?

**Comment by flyx** [comment]
If the current one is the one still open, you can put it in there.

**Comment by rogermc2** [comment]
Have done.
