### ISSUE TITLE
undefined reference to `glEndTransformFeedback@0' on windows 10

### ISSUE THREAD

**Issue by ohenley** [flyx/OpenGLAda#124]
On windows 10, this happen every time I link against libOpenGLAda.a. Output:

gprbuild -d -PC:\Users\ohenley\Desktop\OpenGLAda\examples\ogl_tutorials\02_red_triangle\tutorial_02.gpr -XMode=debug -XLibrary_Type=static -XAuto_Exceptions=enabled -XWindowing_System=windows -XGLFW_Version=3
Link
   [link]         tutorial_02.adb
C:\Users\ohenley\Desktop\OpenGLAda\lib\libOpenGLAda.a(gl-objects-programs.o):gl-objects-programs.adb:(.text+0x1369): undefined reference to `glEndTransformFeedback@0'
collect2.exe: error: ld returned 1 exit status
gprbuild: link of tutorial_02.adb failed
[2018-04-08 14:36:31] process exited with status 4, 100% (91/91), elapsed time: 06.51s

I deleted the code concerning glEndTransformFeedback (End_Transform_Feedback) and it completes.

**Comment by flyx** [comment]
`glBeginTransformFeedback` and `glEndTransformFeedback` must be loaded with function pointers, but are not. I will fix this later today.
