### ISSUE TITLE
ImageMagick and Assim Examples

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#130]
I"m developing some examples that involve ImageMagick and Assim.
However, I think the additional complexity is probably not warranted for OpenGLAda so I plan to setup a separate repository for at least these examples. My intended name is OGL_AdaExamples.
Any suggestions or recommendations are welcome.

**Comment by flyx** [comment]
Eventually, it may be a good idea to put all examples in an own repository. However, having them in the main repository is kinda easier as they also serve as tests.

Anyway, examples that involve additional libs should certainly be in an own repo, so I (over half a year later) approve of your actions :).
