### ISSUE TITLE
Load_Empty_Texture not recognising Depth_Component

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#135]
`Texture_2D.Load_Empty_Texture` no longer seems to recognise `Internal_Format => GL.Pixels.Depth_Component`.
Following code fails:
~~~
        Texture_2D.Bind (aShadow_Map.Texture);
        Texture_2D.Load_Empty_Texture (Level           => 0,
                                       Internal_Format => GL.Pixels.Depth_Component,
                                       Width           => Window_Width,
                                       Height          => Window_Height);
~~~

Error message: 
`raised GL.ERRORS.INVALID_OPERATION_ERROR : gl raise_exception_on_opengl_error.adb:10`.
`Internal_Format => GL.Pixels.Red` is accepted without error.

**Comment by flyx** [comment]
Just a note: I am very sorry that I cannot allocate more time for maintaining OpenGLAda. I am aware of your issues and will try handle them when I find time.

**Comment by rogermc2** [comment]
Appreciated.
Whenever you get time is fine.
Thanks.
