### ISSUE TITLE
Problem with  type Buffer_Target 

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#14]
Mac OSX 10.11.6
Xcode 8.0

GPS 2016 (20160515) hosted on x86_64-apple-darwin14.5.0
GNAT GPL 2016 (20160515-49)

OpenGLAda-master 30 June 2016

I am stuck with a problem trying to use gl.Objects.Buffers.Buffer_Target which I can't solve.

type tTarget is new gl.Objects.Buffers.Buffer_Target(gl.Low_Level.Enums.Element_Array_Buffer);
produces "type derived from tagged type must have extension" which makes sense.

However, when I try 
type tTarget is new gl.Objects.Buffers.Buffer_Target(gl.Low_Level.Enums.Element_Array_Buffer) with null record;
GPS responds by opening System.ads and complaining:
system.ads:1:01: subtype mark required in this context

This also occurs for
type tTarget is new gl.Objects.Buffers.Buffer_Target(gl.Low_Level.Enums.Element_Array_Buffer) with 
record
<record elements>
end record;

 syntax check does not produce the problem:
 gprbuild -c -gnatc -u -eL -P/OpenGL_Projects/GLFW Tutorial/Tutorial 1/glfw_tutorial_1.gpr -XLIBRARY_TYPE=static -XAuto_Exceptions=enabled -XMode=debug buffers.adb -s

The problem occurs when compiling:
gprbuild -c -u -eL -P/OpenGL_Projects/GLFW Tutorial/Tutorial 1/glfw_tutorial_1.gpr -XLIBRARY_TYPE=static -XAuto_Exceptions=enabled -XMode=debug buffers.adb -s

**Comment by flyx** [comment]
`Buffer_Target` is a private type and not meant for instantiation by the user. Just use the constant `GL.Objects.Buffers.Element_Array_Buffer`.

**Comment by rogermc2** [comment]
Thanks flyx.
