### ISSUE TITLE
ALR update/build failure on Mac

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#150]
I am trying to build  OpenGLAda using alire but am having many difficulties.
When I try alr update in any of the OpenGLAda subdirectories I get:
~~~
error: Cannot continue with invalid session:
error:    Failed to load /Ada_Source/OpenGLAda/opengl/alire.toml:
error:    Cannot load manifest openglada, please review contents:
error:    Loading release from manifest: /Ada_Source/OpenGLAda/opengl/alire.toml:
error:    licenses:
error:    license expects an array
~~~
The alire documentation does not seem to address this issue.
This problem is particularly strange as  alr update works on my other Mac.

**Comment by flyx** [comment]
That is very strange. The Alire docs say:

> licenses: mandatory (for indexing) string. A valid [SPDX expression](https://spdx.org/licenses/). Custom license identifiers are accepted with the format: custom-[0-9a-zA-Z.-]+

Therefore, `opengl/alire.toml` is right to specify

    licenses = "MIT"

What OS are you on and what `alr` version are you using?

**Comment by rogermc2** [comment]
OSX 10.13.6  High Sierra
~~~
Alr version: 0.7.1
Alire Library version: 0.7.1
~~~
I'm new to alr and am having quite a battle getting used to it.
Thanks for your assistance.

**Comment by flyx** [comment]
[This Alire PR](https://github.com/alire-project/alire/pull/629) introduced SPDX expression to `licenses` and consequentially, you'll need an `alr` that includes this change. You need at least `alr 1.0.0`, though using the `1.1.x` would probably be preferrable.

**Comment by rogermc2** [comment]
Thanks.
ALR on my other computer is `1.1`
On this computer `which alr` revealed the older version hiding in another directory.
Deleting that fixed things.
OpenGLAda working again!
