### ISSUE TITLE
Test builds fail with _glfwRawMouseMotionSupported undefined

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#151]
When I attempt to build any of the test programs I get the following error:
~~~
Undefined symbols for architecture x86_64:
  "_glfwRawMouseMotionSupported", referenced from:
      _glfw__input__mouse__raw_motion_supported in libGlfwAda.a(glfw-input-mouse.o)
~~~

**Comment by flyx** [comment]
Your GLFW library is too old. PR #149 introduced this binding which requires GLFW 3.3 or newer. I updated the `alire.toml` file to reflect this but depending on your system you need to take manual action to update the library.

**Comment by rogermc2** [comment]
Thanks.
I was getting some alr messages regarding regarding glfw3^3 which I didn't understand.
So, your answer explains this.
I'm now upgrading glfw with brew:
~~~
==> Upgrading 1 outdated package:
glfw 3.2.1 -> 3.3.6
~~~
