### ISSUE TITLE
GL.Objects.Shaders.Info_Log returns Constraint_Error

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#16]
Mac OSX 10.11.6
XCode 8.0
GPS 2016 (20160515) hosted on x86_64-apple-darwin14.5.0
GNAT GPL 2016 (20160515-49)
Build Command:
gprbuild -d -eL -P/OpenGL_Projects/GLFW Tutorial/Tutorial 1/glfw_tutorial_1.gpr -XLIBRARY_TYPE=static -XAuto_Exceptions=enabled -XMode=debug -s -XWindowing_System=quartz
Build Libraries

GLFW Version: 3.2.1 Cocoa NSGL chdir menubar retina dynamic
OpenGL version supported:  3. 3
Renderer: Intel HD Graphics 3000 OpenGL Engine
Primary_Shading_Language_Version: 3.30

In the attached file:
 if Compile_Shader(Vertex_Shader) then
            Put_Line("Vertex shader compiled.");
            Put_Line(GL.Objects.Shaders.Info_Log(Vertex_Shader));
produces:
Vertex shader compiled.
Load_Buffer returned constraint error: raised CONSTRAINT_ERROR : gl-objects-shaders.adb:77 range check failed

I have tried GL.Objects.Shaders.Info_Log in many locations with the same result.

I had to change the file extension from adb to txt to get the file to upload.
[my_buffers.txt](https://github.com/flyx/OpenGLAda/files/632078/my_buffers.txt)

**Comment by rogermc2** [comment]
Thanks for the quick fix.

**Comment by rogermc2** [comment]
Thanks flyx for the quick fix.
What's the easiest way to download the fixed file?
Regards,
Roger

**Comment by flyx** [comment]
Since it has been quite a while since the last release, I released a `v0.4` (see [releases](https://github.com/flyx/OpenGLAda/releases)).

**Comment by rogermc2** [comment]
Thanks.
I've just downloaded your latest version 0.4.
