### ISSUE TITLE
Problem extracting elements from Shaders.Lists.List lists due to discriminated list elements

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#17]
The program builds OK but fails when run with:
Load_Buffer returned constraint error: raised CONSTRAINT_ERROR : gl-objects-shaders.adb:50 length check failed
This occurs only when I include
 Utilities.Show_All_Shader_Program_Data(Shader_Program);
at the end of the Load_Buffer procedure which builds the shader program then draws the main window.
 Utilities.Show_All_Shader_Program_Data(Shader_Program) runs after I close the main window.

I've cut much out of the Show_All_Shader_Program_Data procedure to simplify debugging.
The program runs OK to completion when I delete 
Shader_Source : String := Shaders.Source(Shaders.Lists.Element(List_Cursor));
which I hoped to use to get the current shader's Shader_Type and also seemed (to me so far) to be the simplest way to demonstrate the problem.

procedure Show_All_Shader_Program_Data(aProgram : gl.Objects.Programs.Program) is
        use GL.Objects;
        Shaders_List     : Shaders.Lists.List := Programs.Attached_Shaders(aProgram);
        List_Cursor        : Shaders.Lists.Cursor := Shaders_List.First;
        Shader_Source : String := Shaders.Source(Shaders.Lists.Element(List_Cursor));
    begin
        Put_Line("GL_ATTACHED_SHADERS: ");
        while Shaders.Lists.Has_Next(List_Cursor) loop
            List_Cursor := Shaders.Lists.Next(List_Cursor);
         end loop;
    exception
      when anError : Constraint_Error =>
         Put("Show_All_Shader_Program_Data returned constraint error: ");
         Put_Line(Exception_Information(anError));
      when anError : GL.Errors.Invalid_Operation_Error =>
         Put_Line("Show_All_Shader_Program_Data returned an invalid operation error: ");
         Put_Line(Exception_Information(anError));
      when anError :  others =>
         Put_Line("An exceptiom occurred in Show_All_Shader_Program_Data.");
         Put_Line(Exception_Information(anError));         
    end Show_All_Shader_Program_Data;

I'm surprised the problem doesn't raise a Show_All_Shader_Program_Data exception?
I actually want to print out the  Attached_Shaders list but can't see how to process out the different type of shaders.

Is this enough or do you need the complete Load_Buffer procedure?

**Comment by flyx** [comment]
A minimal working example would be nice for debugging.

**Comment by rogermc2** [comment]
Many thanks again for the quick response.

**Comment by rogermc2** [comment]
The latest OpenGLAda-master doesn't include obj and lib folders required by opengl-glfw.gpr.

**Comment by flyx** [comment]
> The latest OpenGLAda-master doesn't include obj and lib folders required by opengl-glfw.gpr.

The Makefile takes care of that. It is not possible to check in empty folders with git.

**Comment by rogermc2** [comment]
OK.
I use GPS directly on the gpr file which complains about the missing folders.
No problem for me to just add them manually.

**Comment by alkhimey** [comment]
You can use ```-p``` flag when calling gprbuild from command line. It is also possible to pass this flag when building from GPS.

> -p or --create-missing-dirs (Create missing object, library and exec directories)
>
> By default, GPRbuild checks that the object, library and exec directories specified in project files exist. Switch -p instructs GPRbuild to attempt to create missing directories. Note that these switches may be specified in package Builder of the main project, but they are useless there as either the directories already exist or the processing of the project files has failed before the evaluation of the Builder switches, because there is at least one missing directory.```

**Comment by rogermc2** [comment]
Thanks alkhimey.
I added --create-missing-dirs to my GPS Build targets.
Testing showed that a missing bin directory was generated.
