### ISSUE TITLE
Tessellation Patches Not Implemented.

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#19]
I am trying to learn OpenGL from the book OpenGL Superbible which introduces Tessellation quite early.
However, OpenGLAda doesn't seem to support tessellation shader programming as, for example, there is no Patches Connection_Mode item which, apparently, is needed when calling Draw_Arrays for a GSL program incorporating tessellation shaders.
Is there a way around this?
If not I'll skip the section on tessellation as I don't really need it for my own purposes at the moment.

**Comment by flyx** [comment]
Can you specify which C functions exactly are missing in OpenGLAda? I see that for example, `glPatchParameter*` is missing, I can add that. `Tess_Evaluation_Shader` and `Tess_Control_Shader` are available in `GL.Objects.Shaders`. Anything else?

**Comment by flyx** [comment]
By the way, it would be great if you could share your Ada code for others to see how to implement the examples from the book with OpenGLAda.

**Comment by rogermc2** [comment]
So far, glPatchParameter is the only one needed that I'm aware of other than that Connection_Mode needs Patches as indicated by the following from the text book's example code.
glDrawArrays(GL_PATCHES, 0, 3);
I've had a look through some of the OpenGL Superbible tessellation example code and haven't spotted any additional functions.
Using Draw_Arrays(Triangles, 0, 3) produces  GL.ERRORS.INVALID_OPERATION_ERROR : gl-raise_exception_on_opengl_error.adb:23.
The tessellation shader codes compile OK, so I imagine that Draw_Arrays is failing because it expects a Patches Connection_Mode for tessellation programs?
It will be great if you can provide these additions so that I can test them.
I checked my code against the example code and seem to otherwise have everything coded correctly.

I'm happy to share my Ada code.
What would be a good way to do that?
I have a first example based on the text book that I could provide at the moment.
Also a couple based on Anton's OpenGL 4 Tutorials.
I'm not very happy with my current structure for the OpenGL Superbible program which, at the moment, seems a bit clumsy due to my having to derive it from OpenGL Superbible's Application Class framework.
In fact, the reason I started with Anton's OpenGL 4 Tutorials was to understand the GLFW framework that is the basis for OpenGL Superbible's framework which I found difficult to interpret.

**Comment by flyx** [comment]
I think a good way to share the code would be to put it into an `examples` folder in OpenGLAda. I will happily accept PRs.

**Comment by rogermc2** [comment]
Great! Tesselation works.
Attached is my tessellation program.
To run it, the  Default_Directory variable in application.adb will need to be changed.
[Tess.zip](https://github.com/flyx/OpenGLAda/files/653483/Tess.zip)

**Comment by rogermc2** [comment]
If you provide the examples folder, I will put some examples in.
But, first, what are PRs?

**Comment by flyx** [comment]
See [this article][1] for creating a PR. You can create the examples folder yourself.

 [1]: https://gist.github.com/Chaser324/ce0505fbed06b947d962
