### ISSUE TITLE
Make runtime loading more efficient

### ISSUE THREAD

**Issue by flyx** [flyx/OpenGLAda#22]
*runtime loading* is the process of loading pointers to OpenGL functions at runtime. This is done for multiple reasons:

 * Different implementations provide different portions of the OpenGL API. Linking and executing an OpenGL program should be possible even if unused functions are not available.
 * It should be possible for an application to switch to some backup implementation if a fancy feature is not available.
 * On Windows, all functionality not available in OpenGL 1.1 *must* be loaded dynamically because there are no symbols for newer functions available.

The currently implemented runtime loading in OpenGLAda works as following:

 1. All OpenGL functions beyond OpenGL 1.1 are wrapped with generic subroutines from `GL.Runtime_Loading`.
 2. Each time such a subroutine is called, it looks up a string containing the actual OpenGL function name in a hashmap.
 3. If no such key exists, it asks the OS for a function pointer to that OpenGL function and inserts that function pointer into the hashmap.
 4. Finally, it fetches the function pointer from the hashmap, calls it, and returns the result (if any).

While hashmaps are almost `O(1)`, this process is certainly not ideal, since every function call will result in a hashmap lookup. Since OpenGL applications typically care for performance, this should be improved. A possible solution is as follows:

 * Every non-OpenGL-1.1 function in `GL.API` will be transformed into a variable of the respective function pointer type.
 * The code currently calling these functions will call the function pointers.
 * At some point of program execution, OpenGLAda shall query the function pointers from the OS and fill them in to those variables. After that, every call will go direct to the OpenGL function.

The question is where these function pointer variables shall be assigned a value. There are two feasible solutions I can think of:

 1. All function pointers are assigned an appropriate loader subroutine at elaboration time. This will cause the `GL` package *and all dependent packages* to lose `pragma Preelaborate;`. This may break existing code. The loader subroutines will, when called, query the actual function pointer from the OS, *overwrite the function pointer variable*, and then call it. So only the first call results in a slowdown; after that, the OpenGL implementation is called directly. This solution is safer than the second one because it ensures that there are no uninitialized pointer variables that may be dereferenced.
 2. `GL` gains a procedure `Initialize` which will load the function pointers. This will keep `pragma Preelaborate;`, but requires the user to explicitly call it once *after they created an OpenGL context*.
The library [GLEW][1] which does runtime loading for C/C++ goes this way. However, a call to it may be integrated into `GLFW.Create_Window` which seems to be used by most OpenGLAda users. This solution is simpler and more straight-forward; it also makes sure that all workload is placed into the `Initialize` procedure and no lazy loading occurs during the execution.

Since I have no real preference, I'd like to have some opinions on this from current OpenGLAda users (@rogermc2, @onox, @alkhimey, @WickedShell).

 [1]: http://glew.sourceforge.net

**Comment by rogermc2** [comment]
Thanks for this as it's very informative; I've printed it for future reference.
Obviously, I'm too inexperienced in this area to offer advice.

**Comment by onox** [comment]
I was thinking of simply replacing the hash map with an array that maps an enum to `System.Address`. So you can replace:

```ada
Loaded : Function_Maps.Map;
```

with:

```ada
Loaded : array (Reference_ID) of System.Address;
```

where `Reference_ID` is an enum type containing all the function names. I have added a package called `GL.Functions` which contains this type and a mapping of each enum value to a String access:

```ada
Function_Map : constant array (Reference_ID) of String_Access :=
  (GL_Active_Shader_Program                             => new String'("glActiveShaderProgram"),
   ...
```

I have created this file with a Python script. In `GL.API` you have to replace each string with its corresponding enum value (also handled by the Python script).

Loading a function then becomes:

```ada
    Pointer : System.Address := Loaded (ID);
 begin
    if Pointer = System.Null_Address then
       Pointer := Raw_Subprogram_Reference (Function_Map (ID).all);
       Loaded (ID) := Pointer;
    end if;
    return As_Function_Reference (Pointer);
```

So the function name is only needed when the function pointer needs to be queried from the OS. If the pointer has already been loaded, then only the enum value of the function is needed.

I did not have time yet to do benchmarks and see what the difference in performance is.

The only downside is that you need to add an `Initialize` function to execute `Loaded := (others => System.Null_Address);`.

See https://github.com/onox/orka/commit/e00aa758133884a33b5d048a0df3c73f14cdf84a in my OpenGL 4.5 fork.

**Comment by alkhimey** [comment]
My attempt to understand how things are currently working. Please let me know if this is correct.

The functions that are loaded on runtime (apparently there are very few of these) are defined like this:
```   
procedure Vertex_Attrib3 is new Loader.Procedure_With_4_Params
     ("glVertexAttrib3s", Attributes.Attribute, Short, Short, Short);
```

Calling the function will execute the following code:
```
   procedure Procedure_With_3_Params (Param1 : Param1_Type;
                                      Param2 : Param2_Type;
                                      Param3 : Param3_Type) is
      type Procedure_Reference is
        access procedure (Param1 : Param1_Type; Param2 : Param2_Type;
                          Param3 : Param3_Type);
      pragma Convention (StdCall, Procedure_Reference);

      function Load_Procedure is new Load (Procedure_Reference);
      Reference : constant Procedure_Reference
        := Load_Procedure (Procedure_Name);
   begin
      if Reference = null then
        raise Feature_Not_Supported_Exception with Procedure_Name;
      else
        Reference (Param1, Param2, Param3);
      end if;
   end Procedure_With_3_Params;
```

And ```Load_Procedure``` is instantiation of:
```
   function Load (Function_Name : String) return Function_Reference is
      function As_Function_Reference is new Ada.Unchecked_Conversion (
        Source => System.Address, Target => Function_Reference
      );

      Position : Function_Maps.Cursor := Loaded.Find (Function_Name);
   begin
      if Position = Function_Maps.No_Element then
         Load_Function_To_Map (Function_Name, Position);
         if Position = Function_Maps.No_Element then
            Load_Function_To_Map (Function_Name & "ARB", Position);
            if Position = Function_Maps.No_Element then
               Load_Function_To_Map (Function_Name & "EXT", Position);
            end if;
         end if;
      end if;
      return As_Function_Reference (Function_Maps.Element (Position));
   end Load;
```

Which uses the inline```Load_Function_To_Map``` (only if the procedure is not already in the ```Loaded``` map:
```
   procedure Load_Function_To_Map (Function_Name : String;
                                   Position : out Function_Maps.Cursor) is
      Inserted : Boolean;
   begin
      Loaded.Insert (Key      => Function_Name,
                     New_Item => Raw_Subprogram_Reference (Function_Name),
                     Position => Position,
                     Inserted => Inserted);
   end Load_Function_To_Map;
   pragma Inline (Load_Function_To_Map);

```

Which calls the architecture dependent ```Raw_Subprogram_Reference```:
```
   function GL_Subprogram_Reference (Function_Name : String)
                                     return System.Address is
      GL_Function_Name_C : Interfaces.C.Strings.chars_ptr
        := Interfaces.C.Strings.New_String (Function_Name);

      Result : constant System.Address
        := GL.GLX.Get_Proc_Address (GL_Function_Name_C);
   begin
      Interfaces.C.Strings.Free (GL_Function_Name_C);
      return Result;
   end GL_Subprogram_Reference;
```

---
In my opinion, the overhead of loading the procedure first time can be neglected compared the overhead of calling the procedure once it was already loaded. Therefore once ```glVertexAttrib3s``` was loaded, calling ```Vertex_Attrib3``` should execute ```glVertexAttrib3s``` directly.

For example, this can be achieved with subprogram access:
```
type Vertex_Attrib3_Access is 
   access procedure (Index : Attributes.Attribute, V1,V2,V3 : Short);

procedure Vertex_Attrib3_Loader(Index : Attributes.Attribute, V1,V2,V3 : Short) is
   Vertex_Attrib3_Temp : Vertex_Attrib3_Access := Load("glVertexAttrib3s"); -- needs some thinking...
begin
   Vertex_Attrib3 := Vertex_Attrib3_Temp;
   Vertex_Attrib3_Temp(Index, V1, V2, V3);
end;

Vertex_Attrib3 : Vertex_Attrib3_Access := Vertex_Attrib3_Loader;
```

The benefit is that calling ```Vertex_Attrib3_Loader``` second time will behave almost exactly as if no runtime loading have occured.

There are at least two problems with this suggestion though. One is the that ```*_Loader``` procedure should be written for each procedure. The second problem is that there is lazy loading, which you mentioned as undesirable.

Regarding your suggestions the second suggestion is very reasonable from a library user point of view. I think that you should not be afraid to break existing code as there are not a lot of users to the library, and we still can use older versions.

**Comment by flyx** [comment]
I came up with a possible solution. It is currently in `better-runtime-loading`. What I have done is:

 * Replaced `GL.API` and child packages with `*.spec` files that are written in an Ada-like DSL ([example](https://github.com/flyx/OpenGLAda/blob/better-runtime-loading/src/gl/specs/gl-api.spec)). These files define all functions that should be imported by the OpenGL API, be it by a static import or by a dynamic loading mechanism.
 * Wrote a generator that reads those `*.spec` files and generates API packages (`gl-api.ads` and child packages) as well as `gl-load_function_pointers.adb`. The generated API packages contain Ada declarations for statically imported functions and `access procedure/function` variables for dynamically loaded functions. `Load_Function_Pointers` assigns proper values to all those variables.
 * Added `GL.Init` which must be called once and will use `Load_Function_Pointers` to initialize the variables.
 * Modified `Glfw.Init` on both `v2` and `v3` to call `GL.Init`. Surprisingly, this seems to work even though I originally thought an OpenGL context must already exist for loading the functions.
 * Updated project files and added `generate.gpr` which compiles the generator and a `generate` target in the Makefile that updates the generated files.
 * Checked in the generated files so that users do not need to care about generating them.

Please tell me what you think.

**Comment by rogermc2** [comment]
Looks good to my novice understanding.

**Comment by flyx** [comment]
`better-runtime-loading` has now been incorporated into master.
