### ISSUE TITLE
Problem Binding Texture

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#23]
Initially a problem for me but I found a way which may or may not be right.
GL.Objects.Textures.Bind (Target : Texture_Target; Object : Texture'Class);
Is this the correct way of declaring a Texture_Target?
Texture_2D_Target     : GL.Objects.Textures.Texture_Target(GL.Low_Level.Enums.Texture_2D);

**Comment by flyx** [comment]
All texture targets you need are declared as constants in [GL.Objects.Textures.Targets][1]. Only those also provide `Load_Empty_Texture` and `Load_From_Data` (from `GL.Objects.Textures.With_*D_Loader`). Texture targets are not meant to be instantiated by the user.

 [1]: https://github.com/flyx/OpenGLAda/blob/master/src/gl/interface/gl-objects-textures-targets.ads

**Comment by rogermc2** [comment]
I'm still having problems.
GL.Objects.Textures.Targets only seems to declare
Texture_2D       : aliased constant Texture_2D_Target.Fillable_Target;
and
Texture_2D_Proxy : aliased constant Texture_2D_Proxy_Target.Target;
whereas everything I try complains 
expected type "Texture_Target" defined at gl-objects-textures.ads:115
found type "Fillable_Target" defined at gl-objects-textures-with_2d_loader.ads:31, instance at gl-objects-textures-targets.ads:29

I'm trying to implement glBindTexture(GL_TEXTURE_2D, texture);
with texture declared as
Texture :   GL.Objects.Textures.Texture
and initialized with
 Texture.Initialize_Id;
GL.Objects.Textures.Bind(?????, Texture);

Where am I going wrong?

**Comment by flyx** [comment]
You are using the wrong `Bind`. The `Bind` in `GL.Objects.Textures` is defined on `Texture_Target` and therefore does not work on `Fillable_Target`. But `Bind` is a primitive operation of `Texture_Target` and therefore gets automatically inherited when deriving from `Texture_Target`. Hence, `Fillable_Target` inherits the `Bind` procedure.

The simplest thing to do is:

```ada
declare
   use GL.Objects.Textures.Targets;
   Texture : GL.Objects.Textures.Texture;
begin
   Texture.Initialize_Id;
   Texture_2D.Bind (Texture);
   -- ...
end;
```

Using prefix notation and a `use` clause to let the compiler figure out the proper `Bind` to call.

**Comment by rogermc2** [comment]
Thanks Flyx.
Your "simplest thing" solved my problem.
I'm still a bit baffled as to what's happening but I'll study it a bit more and hopefully get to understand.

**Comment by flyx** [comment]
[This](https://en.wikibooks.org/wiki/Ada_Programming/Object_Orientation#Primitive_operations) is a good read on primitive operations and [this](https://en.wikibooks.org/wiki/Ada_Programming/Object_Orientation#More_details_on_primitive_operations) on primitive operations with tagged types.
