### ISSUE TITLE
Problem with Load_Empty_Texture

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#25]
I'm trying to implement
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 1024, 768, 0, GL_RGB, GL_UNSIGNED_BYTE, 0);
in which GL_UNSIGNED_BYTE specifies the data type of the pixel data (GL_RGB).

Texture_2D.Load_Empty_Texture
              (Level => 0, Internal_Format => GL.Pixels.RGB,
               Width => 1024, Height => 768);
raised GL.ERRORS.INTERNAL_ERROR : gl-raise_exception_on_opengl_error.adb:30

gl-raise_exception_on_opengl_error.adb:30 indicates that INTERNAL_ERROR is due to an Invalid_Enum:
when Errors.Invalid_Enum => raise Errors.Internal_Error;

The pixel data type specified by API.Tex_Image_2D is Pixels.Data_Type'First which appears to me to be Byte not Unsigned_Byte (Pixels.Data_Type second).

My investigations indicate that GL_RGB can take that values 0..255 indicating that pixel data type for RGB in this context should be Unsigned_Byte.

Is this the problem?
Probably not; I tried changing  Pixels.Data_Type'First to Pixels.Unsigned_Byte in GL.Objects.Textures.With_2D_Loader.Load_Empty_Texture's call to API.Tex_Image_2D  but the same error occurred.
As usual, am I misunderstanding something?

**Comment by rogermc2** [comment]
I was going to try glTextureStorage2D (or glTexStorage2D) but it doesn't seem to be implemented.
Neither is glTextureSubImage2D (or glTexSubImage2D ); 
Both of these are used in a OpenGL SuperBible texture example.

**Comment by flyx** [comment]
Yes, `glTexStorage2D` is indeed missing. I will add it after migrating to new runtime loading branch.

**Comment by rogermc2** [comment]
Great to hear that the new runtime loading branch is going well, I look forward to trying it out.

**Comment by flyx** [comment]
I added `glTexStorage2D` to master. It is located right besides `Load_Empty_Texture`. As for your error, can you post a minimal working example?

**Comment by rogermc2** [comment]
Thanks Flyx.
As for the error, I've been off trying other tutorials but now I'm back at the error producing one  and am working on producing a minimal example.

**Comment by flyx** [comment]
I can reproduce the problem. However, I cannot figure out what goes wrong.

The [documentation][1] says that `GL_INVALID_ENUM` can be generated in two cases:

> if target is one of the six cube map 2D image targets and the width and height parameters are not equal.

This is obviously not the case because you're using the `Texture_2D` target.

> if type is not a type constant.

This also is not the case, because the `type` parameter is `GL_BYTE`.

You could help me figuring this out by writing corresponding C code and checking whether that works. Unfortunately, I currently do not have much time for looking into this.

 [1]: https://www.opengl.org/sdk/docs/man/html/glTexImage2D.xhtml

**Comment by rogermc2** [comment]
OK. I'll try but it might take me some time.
For how much of it should I write the  corresponding C code?

**Comment by flyx** [comment]
It would suffice to have code until where you call `glTexImage2D` (and check the resulting error).

**Comment by rogermc2** [comment]
Thanks.
I think I'll try copying some C code from the SuperBible book or example code as this is what my program is "translated" from.

**Comment by rogermc2** [comment]
Attached is my attempt at building the C example requested.
I hope, as a novice, that this is OK.
What I noticed in doing this is that:
Load_Empty_Texture calls API.Tex_Image_2D with the Format parameter set to
Format : Pixels.Format = Pixels.Format'First = Color_Index => 16#1900#;

The 16#1900# DISAGREES with 0 which is used in the example code from which I based my test routine on. So, perhaps the might be the problem?

[Minimal Framebuffer Object.zip](https://github.com/flyx/OpenGLAda/files/737330/Minimal.Framebuffer.Object.zip)

**Comment by flyx** [comment]
I fixed the wrong enum types; the enum for framebuffer pixel formats was used instead of an own one for data formats. However, this does not solve the issue.

You C code lacks the generation of a window with a properly versioned OpenGL context. I can only check the difference between C and Ada when the code setup is otherwise equivalent.

**Comment by rogermc2** [comment]
Here's one that generates a window and runs to completion without error.
I'm not sure what you mean by "properly versioned OpenGL context".
I currently have
Glfw.Windows.Hints.Set_Minimum_OpenGL_Version (3, 3);
in accordance with the problem described  above in 
https://github.com/flyx/OpenGLAda/issues/25#issuecomment-271596964

[Minimal Framebuffer Object C.zip](https://github.com/flyx/OpenGLAda/files/738007/Minimal.Framebuffer.Object.C.zip)

**Comment by rogermc2** [comment]
Here's another one in which I have parameterized Test.c:
void test (GLenum target, GLint Mipmap_Level, GLint internalformat,
           GLsizei width, GLsizei height, GLenum format, GLenum type)
which calls:
glTexImage2D (target, Mipmap_Level, internalformat, width, height, 0,
		format, type, NULL);
This displays a window and runs to completion without error.

Is there anything else that I need to try?

[Minimal Framebuffer Object C.zip](https://github.com/flyx/OpenGLAda/files/738057/Minimal.Framebuffer.Object.C.zip)

**Comment by flyx** [comment]
Hum, the Ada code in your recent zips works for me after my fix. Perhaps I actually solved the issue with my commit. Can you try recompiling everything with latest master and see if the error goes away?

**Comment by rogermc2** [comment]
Thats's a bother. I still get the error.
After updating with GitHub Desktop I checked that I'm fully updated by 
:/Ada_Source/OpenGLAda Roger$git pull
Already up-to-date.

I first cleaned the project then rebuilt but Run still responded with:
/OpenGL_Projects/SuperBible/Minimal Framebuffer Object/minimal_framebuffer
OpenGL Version:  3 3 0
Renderer Version: Intel HD Graphics 3000 OpenGL Engine
 Set_Up, Filters set.
An exceptiom occurred in Set_Up.
raised GL.ERRORS.INTERNAL_ERROR : gl-raise_exception_on_opengl_error.adb:30

**Comment by flyx** [comment]
I made a clean copy and compiled it, it still works. Which operating system are you on again?

**Comment by rogermc2** [comment]
OSX 10.11.6
XCode 8.0
GNAT 6.1.0
:~ Roger$/usr/local/bin/g++ -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/lto-wrapper
Target: x86_64-apple-darwin14.0.0
Configured with: ../gcc-4.9-20141029/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 4.9.2 20141029 (prerelease) (GCC)

**Comment by rogermc2** [comment]
Here is a program that uses a thin binding (I think) of glTexImage2D and runs to completion without error on my system.
[Minimal Framebuffer Object Thin.zip](https://github.com/flyx/OpenGLAda/files/762875/Minimal.Framebuffer.Object.Thin.zip)

**Comment by rogermc2** [comment]
I've started on a thick binding based on yours.
so far:
 package pLoader is new GL.Objects.Textures.With_2D_Loader (GL.Objects.Textures.Texture_Proxy);
    procedure Thin_Tex_Image_2D (Target : GL.Low_Level.Enums.Texture_Kind;
                    Level           : GL.Objects.Textures.Mipmap_Level;
                    Internal_Format : GL.Pixels.Internal_Format;
                    Width, Height   : GL.Types.Size;
                    Format          : GL.Pixels.Data_Format;
                    Data_Type       : GL.Pixels.Data_Type;
                    Data            : System.Address);
   pragma Import (StdCall, Thin_Tex_Image_2D, "glTexImage2D");

   --  procedure Thick_Tex_Image_2D (Target : GL.Low_Level.Enums.Texture_Kind;
   procedure Thick_Tex_Image_2D (Object : pLoader.Target;
                    Level           : GL.Objects.Textures.Mipmap_Level;
                    Internal_Format : GL.Pixels.Internal_Format;
                    Width, Height   : GL.Types.Size) is
   begin
        Thin_Tex_Image_2D (GL.Objects.Textures.Texture_Proxy (Object).Kind, Level, Internal_Format, Width, Height,
                           GL.Pixels.Data_Format'First,
                           GL.Pixels.Data_Type'First, System.Null_Address);
   end Thick_Tex_Image_2D;

which works.
I've yet to work out how to do the Object : Target.
All part of thee learning experience.

**Comment by rogermc2** [comment]
First success??
The attached code runs to successful completion on my system.
It seems that glTexImage2D doesn't like Data_Format'First (=> Stencil_Index).
I tracked this down using the C code:
glTexImage2D (target, Mipmap_Level, internalformat, width, height, 0, format, type, NULL);
with the aid of https://www.opengl.org/sdk/docs/man/html/glTexImage2D.xhtml to provide correct parameters according to which format = GL_STENCIL_INDEX should work but, on my system, it produces an error where as GL_RED does not.


[Minimal Framebuffer Object C.zip](https://github.com/flyx/OpenGLAda/files/765585/Minimal.Framebuffer.Object.C.zip)

**Comment by rogermc2** [comment]
However, this similar program which does not involve an intermediate C interface and calls glTexImage2D via pragma Import fails with an INVALID_VALUE_ERROR.
[Minimal Framebuffer Object Thin.zip](https://github.com/flyx/OpenGLAda/files/766447/Minimal.Framebuffer.Object.Thin.zip)

**Comment by flyx** [comment]
`GL_STENCIL_INDEX` may indeed be the culprit, since the documentation says 

> GL_STENCIL_INDEX may be used for format only if the GL version is 4.4 or higher.

You could try to change the value to `RGB` or something in [gl-objects-textures-with_2d_loader.adb](https://github.com/flyx/OpenGLAda/blob/master/src/gl/implementation/gl-objects-textures-with_2d_loader.adb). If that works, please also update the corresponding `*_1d_*` and `*_3d_*` files and make a PR.

**Comment by rogermc2** [comment]
Seems to work.
PR submitted.
Attached is a program that invokes Texture_2D.Load_Empty_Texture and runs to completion without error on my system.
[Minimal Framebuffer Object.zip](https://github.com/flyx/OpenGLAda/files/768137/Minimal.Framebuffer.Object.zip)
