### ISSUE TITLE
OpenGL.Soil build failure under OSX El Capitan, XCode 8.0

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#26]
Compilation of the file : /System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h
fails on my system with:
CGFont.h:53:40: error: initializer element is not constant
 static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;

but kCGFontIndexMax certainly (to me) looks like a constant:
typedef unsigned short CGFontIndex;
static const CGFontIndex kCGFontIndexMax = ((1 << 16) - 2);
static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;

Googling indicates that this failure is not specific to my system.
I see that there are two Frameworks/CoreGraphics.framework/Headers/CGFont.h on my system.
One in /Library/Developer/CommandLineTools and one in /System/Library
with header files dated 8 Feb 2016 in the first and 2 Nov 2016.
I am aware that Apple are forever reorganizing there system file structures but haven't been able to find what their current preferred organization is.
However, a comparison of the two CGFont.h files indicates no difference at least up to line 53.

Any ideas welcome.

**Comment by flyx** [comment]
I need more information to reproduce. Building the SOIL test like this:

```
gprbuild -d -eL -Psoil_test.gpr -XLIBRARY_TYPE=static -XAuto_Exceptions=enabled -XMode=debug -s -XWindowing_System=quartz -p -XGLFW_Version=3
```

works for me. I am also on El Capitan with Xcode 8 (8A218a).

**Comment by rogermc2** [comment]
Thanks flyx.
Your command line also worked for me, so I checked:
which gcc
/usr/bin/gcc
It seems the problem is due to my gcc-6.1.0 compiler
So I ran gprconfig to select gcc-6.1.0 for Ada and /usr/bin for c.
Then added to my GPS Build Target settings:  --config=/Ada_Source/config.cgpr
soil_test.gpr then built successfully and ran OK.
Seems a bug in gcc-6.1.0?
I'm currently building gcc-6.3.0 to check for any improvement.

**Comment by flyx** [comment]
Interesting. I am unsure which gcc my gprbuild uses, my setup is similar to yours. `/usr/gcc` is 4.2.1 for me, which is the old Apple binary.

**Comment by rogermc2** [comment]
For my system:
/usr/bin/gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

gcc-6.3.0 built OK but I had the install prefix wrong.
So rebuilding from scratch!
