### ISSUE TITLE
Problem with Texture_2D.Load_From_Data

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#38]
I'm having a problem with Texture_2D.Load_From_Data which raises CONSTRAINT_ERROR : erroneous memory access
Attached is a minimal program that includes a local C interface to glTexImage2D
which also raises CONSTRAINT_ERROR : erroneous memory access

[Minimal Tex Image C.zip](https://github.com/flyx/OpenGLAda/files/776355/Minimal.Tex.Image.C.zip)

**Comment by flyx** [comment]
`Image'Address` doesn't work, since `Image` is a reference-counted type and thus a reference. So you're handing in the address of a reference, and OpenGL tries to read the texture from there on, which obviously leads to a memory error.

Use `Image.To_Texture (My_Texture, Flags => (others => False));`. If your image comes out upside down, try `(Invert_Y => True, others => False)` for `Flags`. You cannot access the address of the image data's start directly to use it with `Load_From_Data` because it is a SOIL internal.

**Comment by flyx** [comment]
After reading the SOIL implementation, I saw that it makes some choices for you that you may not want. Hence, I will reopen this issue as *make it possible to get a raw pointer to the image data*.

**Comment by rogermc2** [comment]
Thanks for prompt response.
I tried Image.To_Texture (My_Texture, Flags => (others => False));
but this resulted in:
Setup_Textures hello1 loaded state: TRUE
Setup_Textures Width:  400
Setup_Textures Height:  300
Setup_Textures Channels: RGB

Execution terminated by unhandled exception
raised CONSTRAINT_ERROR : erroneous memory access
Load address: 0x1084cc000

which is what I originally tried.

I read in https://open.gl/textures that
"Although SOIL includes functions to automatically create a texture from an image, it uses features that aren't available in modern OpenGL. Because of this we'll simply use SOIL as an image loader and create the texture ourselves."
Ii then gives an example using 
unsigned char * image = SOIL_load_image
 followed by 
glTexImage2D(-------, image);

**Comment by rogermc2** [comment]
I'll have a go at writing my own OpenGLAda loader for this (based on SOIL).
In which case, what OpenGLAda "image" format should I "load into"?

**Comment by flyx** [comment]
You could edit `soil-images.ads` to provide a function

```ada
function Raw_Pointer (Object : Image) return System.Address;
```

and implement it lik

```
return Object.Pointer;
```

and use that. It should work. And if it does, you can make a PR ;).

**Comment by rogermc2** [comment]
Thanks. It seems to have worked!
I'll do a bit more testing before submitting a PR.

**Comment by flyx** [comment]
To improve type safety, instead of using `System.Address`, I added a new type `Image_Source` which is used for the raw data pointer. You can now access it via `Data` function on a SOIL image and use `Load_From_Data` on it.
