### ISSUE TITLE
Unable to push new branch

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#48]
I tried using your procedure but had a couple of problems and am stuck at the moment being unable to push.

# if you do not already have my repo as remote
git remote add upstream https://github.com/flyx/OpenGLAda.git          -- OK
# switching git branches will remove commited files that do not exist
# in the other branch. to carry over the files you want to commit from
# your current branch, save them somewhere else
mkdir tmp && cp -r examples/durian/hello tmp
# now make a new branch based on my master. It will not have all
# your old commits in the history
git checkout -b hello-example upstream/master                                    -- Failed
This command wouldn't work. It complained:
 "fatal: Cannot update paths and switch to branch 'hello-example' at the same time."
I used git branch hello-example to generate the branch then git checkout hello-example which seems to have worked?
# copy back the things you want to commit
cp -r tmp/hello examples/durian
# commit them (you may want to change `.gitignore` before this)
git add examples/durian                                                                          -- OK

After this I ran git commit (based on instructions from git-scm documentation)
# push the branch to your GitHub to be able to make a PR
git push origin hello-example                                                                -- Failed
produced:
remote: Permission to flyx/OpenGLAda.git denied to rogermc2.
fatal: unable to access 'https://github.com/flyx/OpenGLAda.git/': The requested URL returned error: 403
Apparently I don't have write-acces to "origin"?

I deleted my rogermc2/OpenGLAda then forked a new one wjich is currently "clean".
I notice "push the branch to your GitHub" which doesn't seem consistent with "origin" which I understand to be flyx/OpenGLAda. 
 "your GitHub" seems to indicate rogermc2/OpenGLAda? In which case, how do I push to it?

I find the git-scm documentation quite good but difficult to find what to do in a particular situation.
Your procedure helped considerably as a guide to the relevant sections of the documentation.

If I can get this one sorted out, it will provide me with a good recipe for future PRs.
It turns out GitHub Desktop is definitely unsuitable from my point of view.
The command line approach provides a much more obvious indication of how things should be done.
I found the git status command particularly useful. 
Currently git log produces:
commit c9c7e4fe93805ee6cd33f46b17f96e01541941ef
Author: Roger <rogermc@grapevine.com.au>
Date:   Fri Mar 3 15:22:19 2017 +1100

    Updated .gitignore to ignore Durian hello application file.

commit 189fa2d362a9bd5b4188990c0c4e3af871425aaf
Author: Roger <rogermc@grapevine.com.au>
Date:   Fri Mar 3 15:18:15 2017 +1100

    Add new example to Durian: hello

commit be869366036da8ce381ffd5785a080dd7a0baac1
Author: Felix Krause <contact@flyx.org>
Date:   Wed Mar 1 18:40:33 2017 +0100

    More generator improvements

**Comment by flyx** [comment]
> "fatal: Cannot update paths and switch to branch 'hello-example' at the same time."

You forgot to do `git fetch upstream`. I also forgot to add that initially but edited my comment. May it be that you use the E-Mail interface for these discussions? If so, that explains why you didn't see the update. Also, please look at how your message looks on GitHub. I think you agree that it is not very readable.

GitHub processes your text with a Markdown processor. Hence, every line starting with `#` is shown is first-level heading. In my original comment, those were inside a code fragment (starting and ending with ```) so they were shown as code instead of heading. Please be aware of this when writing answers.

Now, I will try to give you an overview of how git works. To give a complete overview, I will probably write some things which you already know.

First of all, to be able to create PRs, you need a fork of my repository on GitHub. This is your `rogermc2/OpenGLAda`. Our repositories on GitHub are, it git-speak, so-called *bare* repositories, meaning that there is no working copy (i.e. write-accessible files that we can change and commit afterwards). This is typical for repositories hosted on servers and actually the only safe setup for remote repositories we want to push to, because there is no currently checked-out branch. (I will skip some details here.)

Now, you want to have a repository clone on your local machine, so you do `git clone git@github.com:rogermc2/OpenGLAda.git`, which will create a new, complete clone of your GitHub repository inside the newly created folder `OpenGLAda` in the current folder. By cloning from your GitHub repository, git will automatically setup a remote called *origin* which points to you GitHub repository. Remotes are URLs where other clones of the same project reside. While you can work on local branches, git will also keep a complete copy of the remote repository in its `.git` folder. If you want to update that copy, you do `git fetch origin`. You can reference branches of the remote repository by prefixing them with the remote's name, e.g. `origin/master`. When you check out a remote branch (e.g. by `git checkout origin/master`, git will tell you that you are on *detached HEAD state*, meaning that you are not on any valid local branch and thus cannot properly make commits. This is because you cannot change a remote branch.

Now, you also want to keep track of changes I make in my repository, which you forked. To be able to access these changes, you add another origin, called *upstream*. The git command for that is `git remote add upstream https://github.com/flyx/OpenGLAda.git`. Note that this time, I use the HTTPS variant because this remote will be read-only (you don't have write access to my repository). Adding this remote will not fetch its content, so you need to follow up with a `git fetch upstream`. Now you will have a complete clone of my repository.

Typically, when doing a PR, you want to base your changes on my current master branch. What you probably did until now was to work on *your* master branch, which has more and more differences to mine the more commits I push. So, a good strategy for creating a new PR is to do three things:

 1. update your clone of my repo: `git fetch upstream`
 2. create a new branch based on the master branch of my repo: `git checkout -b hello-example upstream/master` (read: *checkout* the branch `master` from the remote `upstream` and create a new local branch (`-b`) named `hello-example` based on it)
 3. commit your changes to the new branch.
 4. push the new branch to your remote by doing `git push origin hello-example` (a mere `git push` does not suffice because the branch `hello-example` does not yet exist on `origin`).
 5. Since your branch is now on your GitHub fork, you can create a PR.

As you see, you do not ever commit to the `master` branch of your fork. This is important for our versions to not diverge. However, you can also keep your `master` branch up-to-date with mine by issuing

```
git fetch upstream # update clone of my repo
git checkout master # be sure you are on *your* master branch
git merge --ff-only upstream/master # update your local branch
git push origin master # push your local branch to your GitHub clone
```

Note that I used `--ff-only` which means *only merge this branch if you can do a fast-forward merge, i.e. if there is no need to create a merge commit*. This will be true as long as you do not commit stuff to your master directly. Now, when I accept one of your PRs, all you need to do is to update your master as described above. Then, you see your changes.

Something you will notice when using this workflow is that whenever you create a new branch, the changes of your previous branches will not exist unless I already merged that PR of yours. This is a good thing since it hinders you from creating multiple PRs that contain the same commits. However, there may be situations where you require having the changes from a previous PR. If this occurs, you can either wait for me to merge your PR, or you can merge the branch with the changes you need into your current branch (for example, assume you have a branch `move-common` which moved those common files, and I didn't merge it yet. But for your new PR, you want to have the common files in the new place. So, assuming you already are on your new branch, you do `git merge move-common`, which will merge the commits in the `move-common` branch to the current one. Note that when you create a PR from this branch now before the `move-common` PR has been accepted, the commits from `move-common` will also show up in the new PR. However, they will vanish automatically once the old PR has been accepted.

There are of course more complex workflows, but I think what I described here will work best for our current work.

**Comment by rogermc2** [comment]
Thanks very much for this.
I doubt that I could ever have derived this workflow from git documentation.
A point of clarification on cloning?
I don't clone your GitHub repository at all?
I just clone rogermc2/OpenGLAda?
So I should delete my current OpenGLAda directory (which was cloned from flyx/OpenGLAda) then clone rogermc2/OpenGLAda?
Then proceed with your recommended strategy?
I need to study your comment in greater detail in conjunction with the git descriptions in the git-scm documentation. I'll only use the git-scm documentation to assist my understanding of your description.

One other question.
Can I have more than one branch at a time?
For example, can I have individual branches concurrently active for different projects (examples) or do I have to wait for a PR initiated from one branch to be accepted before creating another branch?
You may have already answered this question in your paragraph commencing "Something you will notice" but It seems a bit complex at this moment and will require more concentration on it before I fully understand it. My current feeling is that I can't have more than one branch at a time.

**Comment by flyx** [comment]
> I don't clone your GitHub repository at all?
> I just clone rogermc2/OpenGLAda?

You fetch my repository later by adding it as `upstream` remote. The process of *cloning* usually means that you create a new repository based on an existing one, and that would be your fork, because that is the destination you want to push to. However, when you have a local repository with multiple registered remotes, it does not make much of a difference which one you originally cloned and which one you added and fetched.

> So I should delete my current OpenGLAda directory (which was cloned from flyx/OpenGLAda) then clone rogermc2/OpenGLAda?
> Then proceed with your recommended strategy?

That would be the easiest way, just make sure that the changes you want to commit are not lost.

> Can I have more than one local branch at a time?

You can have any number of local branches, but you can only have one *current* branch at a time. The content of the current branch is what lies in your working copy (i.e. all files besides the `.git` folder). If you switch the current branch, the content of the working copy changes – but the other branch will still exist inside the `.git` folder.

> For example, can I have individual local branches concurrently active for different projects (examples) or do I have to wait for a PR initiated from one branch to be accepted before creating another branch?

You can certainly have multiple PR branches. Assume you finished your work on one branch, pushed it to GitHub and made a PR. You can then locally resume with `git fetch upstream`, `git checkout -b new-example upstream/master` and are again on a new branch based on my master branch. The files in the working copy will be at the state of my master branch without the additions you made in your previous branch.

You can switch to your previous branch with `git checkout hello-example` and switch forth again with `git checkout new-example`. This will always change the state of the files in the working copy, and it will also change the branch that will be updated when you do a `git commit`. `git checkout` is non-destructive and will issue an error when it would need to delete files in order to operate. In other words, whenever `git checkout` will change the contents of a file, you will be able to undo this change by checking out the previously active branch.

**Comment by rogermc2** [comment]
Thanks again.
This is very informative.
I think I now have a good enough understanding to make progress tomorrow (hopefully). (Its midnight here.)

**Comment by rogermc2** [comment]
I have made two pull requests base on your instructions.
As things seem OK this issue can be closed.
