### ISSUE TITLE
Missing GLFW.Windows procedure Set_Input_Mode for input keys?

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#53]
I need to implement glfwSetInputMode(window, GLFW_STICKY_KEYS, GL_TRUE);
but glfw-api procedure Set_Input_Mode (Window : System.Address;
                             Mode   : Enums.Input_Toggle;
                             Value  : Bool);

doesn't seem to have made it into glfw.windows.

**Comment by flyx** [comment]
Please check whether the now `Glfw.Windows.Set_Input_Toggle` works properly.

**Comment by rogermc2** [comment]
The program compiled and ran OK when I included Main_Window.Set_Input_Toggle (Sticky_Keys, True);
I'm not sure how to fully test it.
It appears to be included in these tutorials as a precautionary measure:
	// Ensure we can capture the escape key being pressed below
	glfwSetInputMode(window, GLFW_STICKY_KEYS, GL_TRUE);

The escape key works  OK and I previously haven't had trouble with it.
However, I seldom use it as I normally close the program using either the Command-Q or, sometimes, the windows close box.
I have occasionally used the escape key just to check that it works.

**Comment by flyx** [comment]
Well as it runs okay, this is a good enough indicator for me that it works. I'll close the issue.
