### ISSUE TITLE
Translation Problem With Vertex Shader

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#59]
[square_test_minimal.zip](https://github.com/flyx/OpenGLAda/files/881846/square_test_minimal.zip)
I have run into a problem involving the drawing of vertical square (plane) using a translation transformation (MV) followed by an orthographic transformation (P). (MVP = P * MV)
The problem is that  the translated square is rendered as a trapezoid instead of a square.
When translating along the x axis, the vertical sides of the rendered object are parallel as expected but, in the horizontal direction, the vertical size decreases from left to right.
This occurs when the matrix multiplication is done in the Ada program and also when it is done in the shader program. 
However, when done in the shader program the effect is worse.
I have checked, using Mathematica, that the MVP matrix generated should transform a square to a square.
The MVP matrix generated by the Ada program also seems correct has it has the scaling factors for both X and Y are equal.
No problem occurs when rotating the square using a rotation transformation followed by an orthographic projection.
I also checked that the scaling transformation works correctly.
Also if I change the square's coordinates to the required translated coordinates then perform only an orthographic projection the square renders correctly.
It is as if the MVP matrix is getting corrupted in being provided to the shader or that the shader operation is faulty.  This seems unlikely as so many other operations occur correctly.
A minimal version of my program is  #attached.
[square_test_minimal.zip](https://github.com/flyx/OpenGLAda/files/881866/square_test_minimal.zip)

**Comment by rogermc2** [comment]
A further test:
Perform translation in the Ada code then supply the translated array ( T * V)  and orthographic transformation P to the shader (actually  (P * I)).
This generates a correct result: A correctly translated square.
So (P * I) * ( T * V) works, whereas
(P * T * I) * V fails, producing a trapezoid instead of a square.
where:
P is the orthographic matrix
T is the transformation matrix
I is the identity matrix
V is the original vertex array
This involved quite a lot of translation back and forth between 3 space and 4 space, despite which a correct result was obtained.

**Comment by rogermc2** [comment]
I have now realized that the trapezium appears when the matrix sent to the shader comprises only the translation matrix.
So, the shader seems to render  T * V as a trapezium, clipped appropriately.
The attachment png file shows the result with the X translation set to 1. 
![clipped_trapezium](https://cloud.githubusercontent.com/assets/12540410/24585256/8b807096-17c9-11e7-9b4f-7266d7ccd8e3.png)

**Comment by flyx** [comment]
fyi, I am currently busy planning to move houses, so I do not have time to help you.

However, I would suggest not to experiment with the visual result, but directly look at the resulting calculated matrix. Did you compare the result of `(P * I) * ( T * V)` with the one of `(P * T * I) * V`? If the former one works, but the latter doesn't, this suggests a numerical difference between those values, and that is probably where the error lies.

**Comment by rogermc2** [comment]
Thanks for your suggestions.
Good luck with your housemove. Response appreciated at whatever your convenience.
Actually, I am doing all this debugging using vector and matrix results.
I only included the graphic in case my description of the end result wasn't clear.
In all cases, so far, the matrices appear correct.
I have also been doing the computations in Mathematica to ensure correct results.
The only thing I haven't been able to do is debug the shader as I have no means or idea of how to.

**Comment by rogermc2** [comment]
Please regard the preceding as commentary only.
I now believe that the problem can be investigated using only translation matrices without the need to involve projection matrices and am modifying my program accordingly.
I appreciate that you have higher priority responsibilities; in particular, house moving.

**Comment by rogermc2** [comment]
I have compared the result of (P * I) * ( T * V) with the one of (P * T * I) * V.
They are the same and neither work.

I have done some tracking of: 
MVP_Location           : GL.Uniforms.Uniform;
MVP_Matrix             : GL.Types.Singles.Matrix4;
GL.Uniforms.Set_Single (MVP_Location, MVP_Matrix); 

GL.Uniforms.Set_Single  (Location : Uniform; Value : Singles.Matrix4 -> 
     API.Singles.Uniform_Matrix4 (Location, 1, Low_Level.False, (1 => Value)); -> 
Uniform_Matrix4 : T43; ->
type T43 is access procedure (P1 : Uniforms.Uniform; P2 : Size; P3 : Low_Level.Bool; P4 : Types.Singles.Matrix4_Array);
type Matrix4_Array is array (Index_Type range <>) of aliased Matrix4;

in which P4type  is a Singles.Matrix4_Array where I expect Singles.Matrix4?
That is, I expected a matrix type, not an array of matrices.
Is this correct?
Or, have I tracked it incorrectly.?

I also tried coding the translation matrix directly into the vertex shader, instead of passing it via a uniform, and that worked correctly.

**Comment by rogermc2** [comment]
Using use GL.Types.Singles.Transpose has solved other problems in this and other examples so it looks like it is the right fix.

**Comment by flyx** [comment]
Good catch! I think the correct fix for this should be to change OpenGLAda's handling of matrices to match that of GLSL, i.e. regarding them as column-major array rather than as row-major array (as it is implemented currently). So, `A(1, 3)` should mean *the value in column 1, row 3* rather than *the value in row 1, column 3*.

Things that need to be fixed are mainly the vector multiplication. I think most of the other operations are orthogonal.

**Comment by rogermc2** [comment]
That makes sense to me.
As this would be internal to OpenGLAda, I imagine that the fact that most texts use row-major array  shouldn't bother the end user?
I presume that the end user will multiply matrices generated by OpenGLAda without knowledge of their actual structure.

**Comment by flyx** [comment]
Please report back if my fix actually fixes the problem.

**Comment by rogermc2** [comment]
Spinning_Cubes etc. still need Transpose.
I've updated my master branch with yours.
Do I need to wait for the quaternions PR to be completed before testing?

**Comment by flyx** [comment]
No, the quaternions PR is orthogonal to this.

Can you check whether the results from the matrix / vector multiplication differ now compared to before? How do you generate the matrices? Perhaps the generation code needs to be fixed now?

**Comment by flyx** [comment]
You need to fix the matrix generation functions in `Maths` package, they all have the wrong index order now.

**Comment by rogermc2** [comment]
Would it be OK to fix by transposing in the matrix generation functions in Maths package?
This would then keep the code consistent with documentation.

**Comment by flyx** [comment]
I would rather have the examples show the „correct“ way of indexing a matrix, since this is something that *will* lead to errors. What documentation are you referring to?

(Reopening issue until fixed in examples)

**Comment by rogermc2** [comment]
I'm talking about the OpenGL textbooks that I use and, from memory, OpenGL documentation on the web.
I checked that using transpose in Maths.Perspective_Matrix works OK with GL.Uniforms.Set_Single (Projection_Location, Projection_Matrix);
But no problem to change the indexing in the Maths routines if that's a better way to do it?

**Comment by flyx** [comment]
Well, from an Ada perspective, the matrix type is now defined as being column-major. If you start filling it using row-major semantics, you change semantics and should therefore use a different type. It is very bad style to use the same type with different semantics (even if you „correct“ them afterwards with *Transpose*).

I think if we provide the matrix generation functions currently in `Maths` as stock functionality, the user will seldom access the matrix manually and thus it won't be a problem. On the long run, OpenGLAda having the same semantics as GLSL may lessen the confusion. Or it may not. Since consequences are hard to predict, I want to go with being consistent with GLSL rather than being consistent with textbooks targeting C – since the connection to GLSL is tighter than that to C.

**Comment by rogermc2** [comment]
OK.
I'm making the changes now.

**Comment by rogermc2** [comment]
I'm having trouble with rotations about X and Y axes.
I've gone back to just transposing the maths.matrices to check it out.
I plan to change to the column major version once I find out what's wrong with the rotations.

**Comment by rogermc2** [comment]
The product of the transpose of two matrices A and B is given by T(A)*T(B) = T(BA).
I'm wondering if my problem has something to do with this?

**Comment by rogermc2** [comment]
Implemented, tested and pushed.

**Comment by flyx** [comment]
Closing this since it seems to be fixed with recent PR.
