### ISSUE TITLE
opengl-glfw.gpr does not link with libdl

### ISSUE THREAD

**Issue by alkhimey** [flyx/OpenGLAda#6]
I got the following error:

```
$make tests
mkdir -p bin
gprbuild  -p -P glfw_test.gpr -XWindowing_System=x11 -XGLFW_Version=3
gcc-4.6 glfw_test-monitors.o -lglfw3 -pthread -lm -lXcursor -lXxf86vm -lXrandr -lXinerama -lXi -lGL -lX11 -o glfw_test-monitors
/usr/bin/ld: //usr/local/lib/libglfw3.a(glx_context.c.o): undefined reference to symbol 'dlopen@@GLIBC_2.1'
//lib/i386-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
gprbuild: link of glfw_test-monitors.adb failed
```

Adding "-ldl" flag to linker options of opengl-glfw.gpr file solved the problem.

**Comment by flyx** [comment]
Which version of GLFW are you linking against exactly?

This is from the current GLFW Readme.md:

> [GLX] Added dependency on libdl on systems where it provides dlopen

As I see it, they added this dependency recently and did not yet release a version that requires it. Did you use their current GitHub HEAD?

**Comment by alkhimey** [comment]
Yes this is correct, I compiled and installed it from the git repository.

**Comment by flyx** [comment]
Please report back if this fix works. I currently don't have the environment available for testing it.

**Comment by alkhimey** [comment]
Fixed it.
