### ISSUE TITLE
GL.Types.Single_Pointers doesn't work

### ISSUE THREAD

**Issue by onox** [flyx/OpenGLAda#7]
It seems OpenGLAda only supports VBO's with data of which each row has at most four elements. I'm trying to get it to accept arbitrary number (n) of elements. But so far it doesn't work.

I'm trying to port the `gl_test-opengl3.adb` example from using a `Singles.Vector3_Pointers` to a `Single_Pointers` type. In `Load_Data` I replace `Triangle1` with:

```ada
Triangle1 : constant Single_Array
  := (-0.3,  0.5, -1.0,
      -0.8, -0.5, -1.0,
       0.2, -0.5, -1.0);
```

For now each row still has three elements, but I want to increase this later to six or eight.

In the body I have:

```ada
Load_Vectors (Array_Buffer, Triangle1, Static_Draw);
GL.Attributes.Set_Vertex_Attrib_Pointer (Attrib_Pos, 3, Single_Type, 3, 0);
```

What I get is a black screen instead of the colored triangle (I have removed the red triangle). Am I doing something wrong?

I have a second question: are the last two parameters of `Set_Vertex_Attrib_Pointer` the number of elements or the bit size of the rows? In C++ I have something like (with rows having eight elements, pointing at the last two elements, skipping the first six):

```cpp
glVertexAttribPointer(texAttrib, 2, GL_FLOAT, GL_FALSE, 8*sizeof(float), (void*)(6*sizeof(float)));
```

Do I need to manually use `'Size` or `System.Storage_Unit`?

**Comment by flyx** [comment]
`Single_Array` seems to miss `pragma Convention(C, Single_Array)` in `gl-types.ads`. Could you try to add that (also for the other array types there) and check if it works? I currently do not have set up a dev environment for OpenGLAda.

`Set_Vertex_Attrib_Pointer` takes `Stride` and `Offset` as number of bytes. So if you want to have an offset of 3 singles between values, you would need to write `3 * Single'Size / System.Storage_Unit`. This isn't pretty and could probably be improved [here][https://github.com/flyx/OpenGLAda/blob/master/src/gl/implementation/gl-attributes.adb#L30]. You'd need to provide provide one `when` clause for each type and multiply the size values with the size of the given type in bytes. I'd happily accept a pull request for that.
