### ISSUE TITLE
Many examples are choking

### ISSUE THREAD

**Issue by ohenley** [flyx/OpenGLAda#72]
On windows 10, every ogl_tutorials gives the following:

OpenGL version supported:  3. 2
Renderer: GeForce GTX 750 Ti/PCIe/SSE2
Primary_Shading_Language_Version: 1.50 NVIDIA via Cg compiler

An exception occurred in Setup.
An exception occurred in Render.
An exception occurred in Main_Loop.
Tutorial_03 returned a constraint error: Exception name: CONSTRAINT_ERROR
Message: gl-objects-programs.adb:274 access check failed

Note: Actually, gl_test-immediate.exe works but every other gl-test-xxxxx returns an acces check failed.

Am I doing something wrong?

Thx.

**Comment by ohenley** [comment]
hummm it looks like a bad match between Windows 10/Gnat 2015/OpenGL because Globe3D is also choking... and I just build it yesterday on windows 7 and everything was running fine.

**Comment by flyx** [comment]
Have you tried a newer compiler version (2016 or one of MinGW's binaries)?

**Comment by ohenley** [comment]
Yes installed 2016... still crashing.

**Comment by flyx** [comment]
I just tried with GNAT GPL 2017 but that does not even find the glfw dll anymore for some reason. Perhaps you can try with that version (has been released some days ago).
