### ISSUE TITLE
How do I get scroll data?

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#76]
I have been unable to figure out how to get scroll x, y data as a replacement for the C callback routine
~~~
void scroll_callback(GLFWwindow* window, double x, double y);
~~~
How to implement?

**Comment by rogermc2** [comment]
Also, how to implement?
~~~
void cursor_position_callback(GLFWwindow* window, double x, double y)
{
    if (glfwGetInputMode(window, GLFW_CURSOR) == GLFW_CURSOR_DISABLED)
~~~

**Comment by flyx** [comment]
Just so you know I am aware of your issues… I am very sorry that I do not find the time to react to them. I hope this will get better soon.

**Comment by rogermc2** [comment]
No problem.
Whenever its convenient for you is fine.

**Comment by flyx** [comment]
This is implemented in the GLFW 3 API. You basically do:

    type My_Window_Type is new Glfw.Windows.Window with null record;

    overriding procedure Mouse_Scrolled (Object : not null access Window;
                             X, Y   : Input.Mouse.Scroll_Offset);

And then somewhere in your code:

    My_Window.Enable (Glfw.Windows.Callbacks.Mouse_Scroll);

After that, the implementation of your `Mouse_Scrolled` procedure will be called on mouse scrolling.

**Comment by flyx** [comment]
Closing this since functionality is already there.
