### ISSUE TITLE
Unable to build OpenGLAda libraries.

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#80]
Suddenly my builds are failing when attempting to build OpenGLAda libraries.
I tried on a couple of my branches with the same result.

gprbuild -d -eL -P/Ada_Source/OpenGLAda/opengl.gpr -XLIBRARY_TYPE=static -XAuto_Exceptions=enabled -XMode=release -XWindowing_System=quartz -s -XWindowing_System=quartz --create-missing-dirs --config=/Ada_Source/config.cgpr
Build Libraries
   [gprlib]       OpenGLAda.lexch
gprlib: unknown section: [PROJECT DIRECTORY]
gprbuild: could not build library for project opengl

**Comment by rogermc2** [comment]
I recently moved to GPS GPL 2016 which seems to be the problem.
It worked OK for a few days then, today, this problem suddenly occurred.
I reset the toolchain to /opt/gcc-6.1.0/bin and this fixed the problem.
So there seems to be a problem with the GPS GPL 2016 gnat system?

**Comment by flyx** [comment]
2016 is not the recent release anyway, try with 2017.

**Comment by rogermc2** [comment]
Actually it is 2017, from Help -> about:
GPS 2017 (20170515) hosted on x86_64-apple-darwin14.5.0
GNAT GPL 2017 (20170515-63)
The Application name in the Mac menu line is GPS GPL 2016!

**Comment by flyx** [comment]
Incompatibility with GNAT GPL 2017 is unfortunate, but we already have the incompatibility with GNAT GPL 2016 on OSX, so I guess it just continues a tradition.

For a more helpful comment: This error seems to stem from [this line](https://github.com/AdaCore/gprbuild/blob/master/src/gprlib.adb#L2009), maybe you can backtrack from there what's going wrong.

**Comment by flyx** [comment]
This part of the gprlib seems to read a library exchange file. It may well be that the format of those simply changed, and the error occurs when gprbuild tries to read an exchange file that was generated by a previous version. try to clean everything and compile anew.

**Comment by rogermc2** [comment]
I deleted the current /usr/local/gnat plus a few other associated things.
Downloaded a fresh copy, installed and so far its working.
The unarchived download is    gnat-gpl-2017-x86_64-darwin-bin
This is the same as the previous one that eventually failed; so its wait and see for a few days.

**Comment by elmindreda** [comment]
Parsing, matching, remapping and state retrieval are working. There's still a little work left to do, but most of it is done.

Below is the raw state of an Xbox 360 controller on Linux (top) and filtered through a mapping (bottom).

![mapping](https://user-images.githubusercontent.com/133714/27479596-d4bbfc5e-5814-11e7-8308-c592b3a6bf94.png)

The current (but not necessarily final) API is as follows:
```c
#define GLFW_GAMEPAD_DPAD_UP        0
#define GLFW_GAMEPAD_DPAD_RIGHT     1
#define GLFW_GAMEPAD_DPAD_DOWN      2
#define GLFW_GAMEPAD_DPAD_LEFT      3
#define GLFW_GAMEPAD_A              4
#define GLFW_GAMEPAD_B              5
#define GLFW_GAMEPAD_X              6
#define GLFW_GAMEPAD_Y              7
#define GLFW_GAMEPAD_LEFT_THUMB     8
#define GLFW_GAMEPAD_RIGHT_THUMB    9
#define GLFW_GAMEPAD_LEFT_BUMPER    10
#define GLFW_GAMEPAD_RIGHT_BUMPER   11
#define GLFW_GAMEPAD_START          12
#define GLFW_GAMEPAD_BACK           13

#define GLFW_GAMEPAD_LEFT_X         0
#define GLFW_GAMEPAD_LEFT_Y         1
#define GLFW_GAMEPAD_RIGHT_X        2
#define GLFW_GAMEPAD_RIGHT_Y        3
#define GLFW_GAMEPAD_LEFT_TRIGGER   4
#define GLFW_GAMEPAD_RIGHT_TRIGGER  5

typedef struct GLFWgamepadstate
{
    char buttons[14];
    float axes[6];
} GLFWgamepadstate;

int glfwParseGamepadMapping(const char* string);
int glfwJoystickIsGamepad(int jid);
int glfwGetGamepadState(int jid, GLFWgamepadstate* state);
```

`glfwParseGamepadMapping` can handle both a single mapping, multiple mappings separated by newlines and the whole unmodified `gamecontrollerdb.txt` with comments and everything.

Feedback on the public API is very welcome, the earlier the better but any time before release works.

**Comment by rogermc2** [comment]
Clean and reinstall seems to have fixed the problem.

**Comment by rogermc2** [comment]
Problem has reappeared.
