### ISSUE TITLE
Draw_Elements does not allow you to specify the offset of the index buffer.

### ISSUE THREAD

**Issue by AdaDoom3** [flyx/OpenGLAda#93]
I think this is a major feature of the API and should not be zero'ed out as it is currently.

**Comment by flyx** [comment]
What exactly is missing? `GL.Objects.Buffers` provides `Array_Buffer` and `Element_Array_Buffer` and has `Draw_Elements`.

**Comment by AdaDoom3** [comment]
Indeed, my mistake. I was looking at the "element array buffer offset" parameter being set to Low_Level.Zero as it was labeled "Indicies" when you imported it.

`procedure Draw_Elements (Mode : Connection_Mode; Count : Size; Index_Type : Unsigned_Numeric_Type; Indices : Low_Level.Zero);`

**Comment by AdaDoom3** [comment]
Thanks for the quick response BTW : )

**Comment by flyx** [comment]
Ah yes, that is one of those very strange parts of OpenGL where the function takes a void pointer which actually is an integer offset for whatever reason. So you actually found a missing feature: OpenGLAda does not allow you to specify that offset. I'll rename the issue, this should be fixed.

**Comment by AdaDoom3** [comment]
On a related note, I think you should have a similar package GL.Objects.Vertex_Array for Indices like "GL.Objects.Index_Array" which uses Draw_Elements etc
