### ISSUE TITLE
High-Level API for text rendering

### ISSUE THREAD

**Issue by flyx** [flyx/OpenGLAda#99]
Using the FTGL binding is not flexible enough and should be deprecated. Instead, we should implement an own high-level text rendering API based on the new FreeType binding.

I started implementing this and got it to a level where text is rendered onto a texture. However, it is not *completely* working and I hope @rogermc2 can be of some assistance since my OpenGL is a bit rusty.

Current test program can be compiled with `opengl-freetype-test.gpr`. It depends on [Strings_Edit][1] for parsing UTF-8 input (so that we can render arbitrary unicode characters). TODOs:

 * [x] figure out why the example only renders the text correctly after resizing the window once.
 * [x] figure out how to properly color the texture the text is rendered into.
 * [x] do some renaming. `GL.FreeType` should probably be simply `GL.Text`. Some types therein are also in need of renaming.
 * [x] provide a way for the user to configure text size (currently hardcoded).
 * [x] maybe do not render to a color texture, but instead to a red-only texture like the original character bitmaps are.
 * [x] catch the case that a character is not available in the font. Maybe render a `?` instead.
 * [x] documentation

I look forward to your comments, @rogermc2 .

 [1]: http://www.dmitry-kazakov.de/ada/strings_edit.htm

**Comment by rogermc2** [comment]
Great! I'll have a look at it today.

**Comment by flyx** [comment]
Execute `gprclean` on the project (GPS can do it), that usually fixes those errors.

I intentionally put the shaders into the program source because `GL.FreeType` is a library and I cannot assume anything about the packaging of the resulting program, so I cannot make sure that the shader source files are spread alongside the library, and if so, at which path they can be found.

You can install `strings_edit` by downloading its source and executing `gprinstall` which places it in a location where gprbuild can find it automatically.

**Comment by rogermc2** [comment]
I have tried `gprclean` but it didn't solve the problem, but I'll leave that problem until after I get `strings_edit` properly installed.
I started with a fresh copy of `strings_edit`, then, using the instructions in 'http://www.adacore.com/adaanswers/gems/gem-158-gprinstall/' tried 
`gprbuild -p strings_edit.gpr` then
~~~
:/Ada_Source/strings_3_2 Roger$gprinstall -p strings_edit.gpr 
Install project Strings_Edit
file strings_edit-integers-superscript.o exists, use -f to overwrite
:/Ada_Source/strings_3_2 Roger$gprinstall -f -p strings_edit.gpr 
Install project Strings_Edit
file /Ada_Source/strings_3_2/strings_edit-text_edit.o does not exist, build may not be complete
~~~

If I try gprinstall first, I get:
~~~
:/Ada_Source/strings_3_2 Roger$sudo gprinstall -p strings_edit.gpr 
Install project Strings_Edit

Execution terminated by unhandled exception
raised ADA.IO_EXCEPTIONS.NAME_ERROR : /Ada_Source/strings_3_2/strings_edit-float_edit.o: No such file or directory
Load address: 0x104089000
Call stack traceback locations:
0x10443269f 0x10440094e 0x1040c92dd 0x1040db69f 0x10413562c 0x10408b988 0x104458771
~~~
 Any idea what's wrong?

**Comment by flyx** [comment]
I have never had any problems with `gprinstall`, so I don't know what goes wrong here. Does the `gprbuild` step produce any warnings?

**Comment by rogermc2** [comment]
It only seems to do compiles, no warnings or errors:
~~~
Ada_Source/strings_3_2 Roger$sudo gprbuild -p strings_edit.gpr 
Password:
Compile
   [Ada]          strings_edit-float_edit.adb
   [Ada]          strings_edit-integers-superscript.ads
-
-
-
   [Ada]          strings_edit-utf8-subscript.adb
   [Ada]          strings_edit-streams-generic_integer.adb
:/Ada_Source/strings_3_2 Roger$
~~~

**Comment by flyx** [comment]
does it compile `strings_edit-text_edit.adb`, since `strings_edit-text_edit.o` seems to be missing?

**Comment by rogermc2** [comment]
`strings_edit-text_edit.adb` is not in the gprbuild list of compilations but is definitely in the strings_3_2 directory.

**Comment by flyx** [comment]
Then I would try to figure out why it is not part of the compilation, since that is what `gnatinstall` chokes on later. You could ask on comp.lang.ada since the author of Strings_Edit hangs around there.

**Comment by rogermc2** [comment]
Thanks. Now that I know where things are going wrong I'll try and fix it before seeking further help.

**Comment by rogermc2** [comment]
I think I've found the solution.
I apparently need to use  Dmitry's GPS LIBRARY INSTALLER, not gprinstall.

**Comment by flyx** [comment]
Interesting, I did not need to use that. Anyway, just pushed an update that improves everything. Still some work left to be done.

**Comment by rogermc2** [comment]
Maybe something has been changed.
The gpr file only contains source file data. There are no library name or library directory entries so that it seems that only compilation was occurring with no linking or binding.

**Comment by rogermc2** [comment]
Also doesn't find the sampler files.
I had to provide full path names to get it to work. Obviously not a solution but I couldn't find relative path names that worked.

**Comment by flyx** [comment]
The relative path names I provided work for me on macOS High Sierra when executing the program from within the `bin` directory. Your error hints to an external cause (it's an Objective-C error message), you could try updating your glfw library. Which GNAT are you using?

**Comment by rogermc2** [comment]
The error actually occurs when I quit the program.
I just changed to GNAT 2017.
Now the error is:
~~~
libc++abi.dylib: terminating with uncaught foreign exception

raised PROGRAM_ERROR : unhandled signal
~~

**Comment by rogermc2** [comment]
Relative paths work with  `../tests/` replaced by  `tests/`

**Comment by flyx** [comment]
You need to start the executable with `bin` as working directory to make `../tests/` work. I do it this way because when launching from within GPS, you can select to run from the executable's dir – otherwise, it'll start from the working directory of GPS which could be anywhere. So making it work from the directory where the executable is located seems the sensible way to go.

**Comment by rogermc2** [comment]
My 'edit_strings` woes seem to have actually been caused by using an "old" GNAT.
Switching to GNAT 2017 is what fixed it.

**Comment by flyx** [comment]
Good to hear! I still wonder where the error on exit comes from. It works fine for me on both macOS and Windows.

btw, I pushed some renaming and API improvement earlier – the package is now called `GL.Text`.

**Comment by rogermc2** [comment]
I now have it working using  `../tests/` and no exit error, at least on one computer but not the other!

**Comment by flyx** [comment]
Feature-wise, I have the code ready. Only things missing are documentation and information about whether your problems can be solved by improving the implementation.

**Comment by rogermc2** [comment]
Its working OK on one of my computers.
Except that I get the following build warnings:
~~~
warning: "gl-text.adb" has dynamic elaboration checks and with's
warning:   "strings_edit.ads" which has static elaboration checks
warning: "gl-text.adb" has dynamic elaboration checks and with's
warning:   "strings_edit-utf8.ads" which has static elaboration checks
~~~
I was getting these warnings on previous versions.
I'll check the other computer later.

**Comment by rogermc2** [comment]
I don't get the build warnings on my other computer but on program termination I get:
~~~
libc++abi.dylib: terminating with uncaught foreign exception

raised PROGRAM_ERROR : unhandled signal
[2017-10-28 12:18:47] process exited with status 1, elapsed time: 03.54s
~~~

**Comment by flyx** [comment]
I fixed the warnings (you may need to explicitly clean your project before compiling for it to go away). Maybe it also fixes the error?

If not, can you check whether you have different GLFW or compiler versions on the two machines?

**Comment by rogermc2** [comment]
Hasn't fixed the error.
Yet to test the warnings.

**Comment by rogermc2** [comment]
On this machine:
~~~
MacBook-Air:OpenGLAda rogermcmurtrie$ brew list glfw
/usr/local/Cellar/glfw/3.2.1/include/GLFW/ (2 files)
/usr/local/Cellar/glfw/3.2.1/lib/libglfw.3.2.dylib
/usr/local/Cellar/glfw/3.2.1/lib/cmake/ (4 files)
/usr/local/Cellar/glfw/3.2.1/lib/pkgconfig/glfw3.pc
/usr/local/Cellar/glfw/3.2.1/lib/ (2 other files)
~~~
Do I need to check something else?

**Comment by flyx** [comment]
Looks fine. I am currently at a loss about what may be wrong. Need to find a way to inspect this „foreign exception“ that arises. Does the program run correctly apart from that error at termination?

**Comment by rogermc2** [comment]
Seems to be working OK now.
Actually, the first time I ran it on the other machine after clean and rebuild, the error occurred but after that ran OK.
No other problems.
However, the text in the source code is:
~~~
"The quick brÃ¶wn fÃ¼x jumpÃ over the lazy ð©dog."
~~~
The displayed text is much better. The o in browns displayed with two dots over the o
The o in fox is displayed as u  with two dots above. 
The s in jumps is displayed as the Greek letter beta.
dog is preceded by a ?

**Comment by flyx** [comment]
The text looks scrambled because it is encoded in UTF-8. Sadly, GNAT does a very poor job at supporting UTF-8 as input encoding. The only way I got it to work is to *not* use the switch `-gnatW8` (which activates UTF-8 decoding when parsing) because that re-encodes the String in ANSI. Since GPS does not support editing source files encoded in UTF-8, the text looks broken.

Basically, I replaced some letters with umlauts / other non-ASCII characters to check whether UTF-8 support is working. The string correctly reads

    The quick bröwn füx jumpß over the lazy 💩dog.

First time I ever used these emoji things – I basically needed a character which is guaranteed to not exist in the font I loaded, to check whether it gets substituted with `?` which is the fallback for such cases. Maybe I should change that emoji to an, um, more neutral one ^^.

Btw, the `ß` is a german letter with a long history, dating back to a ligature merge in Fraktur writing, see [here](https://en.wikipedia.org/wiki/ß).

**Comment by rogermc2** [comment]
OK. The string is being displayed correctly assuming that the emoji thing should be replaced by a ?.
Your reference to  ß is interesting, albeit complex!

**Comment by flyx** [comment]
Good, so I assume there are no further obvious errors.

I decided to do away with `opengl_shared.gpr` because everything that depends on it also depends on `opengl.gpr`, so I can place everything in there. I will make sure that example projects that depend on it also get updated.

I may do a new release soon to announce the availability of the new font rendering tools – both the basic FreeType binding and `GL.Text`.

**Comment by rogermc2** [comment]
I'll have a go at using the new font rendering tools in my current project in place of my current text rendering program.

**Comment by flyx** [comment]
Just found [this](http://www.valvesoftware.com/publications/2007/SIGGRAPH2007_AlphaTestedMagnification.pdf) which looks totally awesome, but I will probably never have time to implement it :(

**Comment by rogermc2** [comment]
I've started on the new example.
A problem. I can't see how to set the position of the text on the screen?

**Comment by flyx** [comment]
Docs are online, tell me whether you have problems with using `GL.Text`. If not, we can close this issue.

**Comment by rogermc2** [comment]
So far, no problems with `GL.Text`.
Not quite got my first use of it working but `GL.Text` seems OK.

**Comment by rogermc2** [comment]
I have a problem in that I can't get it render two lines from two successive calls of my implementation routine which is similar to your test program except that much of the text setup occurs on each iteration of my main loop.
At the moment, I can only get my example to display the first of the two lines.
This process has worked without problem in my previous text rendering example.
Basically my current example is based on integrating relevant parts of your test program into my previous text rendering example.
The problem seems to involve the blending functions which I don't fully understand yet. Seems to be doing something to the frame buffer.
Could you check by amending your test program to render two separate lines involving two calls to `Draw_Arrays` in the loop. I imagine that this might involve two separate calls to `Load_Data` and associated functions in the loop?

**Comment by rogermc2** [comment]
Could you amend your test to render two separate strings at different places in the window.
I am having trouble rendering multiple strings, possibly something to do with the blend function?
In my geometric algebra project, in which I am using my original string rendering code, I render a dozen or so strings in the window without problem. These strings actually provide labels to small diagrams.

**Comment by rogermc2** [comment]
I have now used `GL.Text` in my geometric algebra project rendering a display that includes 24 separate text strings.
So definitely can close.

**Comment by rogermc2** [comment]
Wonderful news!
